-- Migration 001: Initial schema
-- All UUIDs generated by PostgreSQL gen_random_uuid() (requires pgcrypto or pg 13+)

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  email        TEXT         NOT NULL UNIQUE,
  display_name TEXT         NOT NULL,
  avatar_url   TEXT,
  coin_balance INTEGER      NOT NULL DEFAULT 0 CHECK (coin_balance >= 0),
  apple_id     TEXT         UNIQUE,
  google_id    TEXT         UNIQUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_email    ON users (email);
CREATE INDEX idx_users_apple_id ON users (apple_id) WHERE apple_id IS NOT NULL;
CREATE INDEX idx_users_google_id ON users (google_id) WHERE google_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash  TEXT        NOT NULL UNIQUE,
  expires_at  TIMESTAMPTZ NOT NULL,
  revoked_at  TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------------
-- game_definitions
-- ---------------------------------------------------------------------------
CREATE TABLE game_definitions (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  game_type   TEXT        NOT NULL,
  config      JSONB       NOT NULL,
  difficulty  TEXT        NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_game_definitions_game_type ON game_definitions (game_type);

-- ---------------------------------------------------------------------------
-- shows
-- ---------------------------------------------------------------------------
CREATE TABLE shows (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  title          TEXT        NOT NULL,
  scheduled_at   TIMESTAMPTZ NOT NULL,
  status         TEXT        NOT NULL DEFAULT 'scheduled'
                             CHECK (status IN ('scheduled', 'lobby', 'live', 'completed', 'cancelled')),
  game_sequence  JSONB       NOT NULL DEFAULT '[]',
  player_count   INTEGER     NOT NULL DEFAULT 0,
  prize_pool     INTEGER     NOT NULL DEFAULT 0 CHECK (prize_pool >= 0),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_shows_status       ON shows (status);
CREATE INDEX idx_shows_scheduled_at ON shows (scheduled_at);

-- ---------------------------------------------------------------------------
-- show_participants
-- ---------------------------------------------------------------------------
CREATE TABLE show_participants (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  show_id      UUID        NOT NULL REFERENCES shows (id) ON DELETE CASCADE,
  status       TEXT        NOT NULL DEFAULT 'registered'
               CHECK (status IN ('registered', 'active', 'eliminated', 'winner')),
  round_reached INTEGER    NOT NULL DEFAULT 0,
  coins_earned  INTEGER    NOT NULL DEFAULT 0,
  joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, show_id)
);

CREATE INDEX idx_show_participants_show_id  ON show_participants (show_id);
CREATE INDEX idx_show_participants_user_id  ON show_participants (user_id);
CREATE INDEX idx_show_participants_status   ON show_participants (show_id, status);

-- ---------------------------------------------------------------------------
-- coin_transactions
-- Wallet mutations use SELECT ... FOR UPDATE on users.coin_balance.
-- idempotency_key enforces exactly-once semantics.
-- ---------------------------------------------------------------------------
CREATE TABLE coin_transactions (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  amount           INTEGER     NOT NULL, -- positive = credit, negative = debit
  type             TEXT        NOT NULL
                   CHECK (type IN ('iap_purchase', 'show_winnings', 'show_entry_fee', 'bonus_grant', 'refund')),
  reference_id     TEXT,
  idempotency_key  TEXT        NOT NULL UNIQUE,
  balance_after    INTEGER     NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_coin_transactions_user_id ON coin_transactions (user_id, created_at DESC);
CREATE INDEX idx_coin_transactions_type    ON coin_transactions (type);

-- ---------------------------------------------------------------------------
-- play_clips
-- ---------------------------------------------------------------------------
CREATE TABLE play_clips (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  show_id     UUID        NOT NULL REFERENCES shows (id) ON DELETE CASCADE,
  round_index INTEGER     NOT NULL,
  game_type   TEXT        NOT NULL,
  media_url   TEXT        NOT NULL,
  hls_url     TEXT,
  status      TEXT        NOT NULL DEFAULT 'processing'
              CHECK (status IN ('processing', 'ready', 'archived')),
  play_count  INTEGER     NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (show_id, round_index)
);

CREATE INDEX idx_play_clips_show_id ON play_clips (show_id);
CREATE INDEX idx_play_clips_status  ON play_clips (status);

-- ---------------------------------------------------------------------------
-- clip_play_sessions
-- ---------------------------------------------------------------------------
CREATE TABLE clip_play_sessions (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  clip_id      UUID        NOT NULL REFERENCES play_clips (id) ON DELETE CASCADE,
  served_at    BIGINT      NOT NULL, -- Unix ms, server-authoritative
  completed_at TIMESTAMPTZ,
  score        INTEGER,
  client_ts    BIGINT,               -- client-reported, anti-cheat only
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_clip_sessions_user_id ON clip_play_sessions (user_id, created_at DESC);
CREATE INDEX idx_clip_sessions_clip_id ON clip_play_sessions (clip_id);

-- ---------------------------------------------------------------------------
-- feature_flags
-- ---------------------------------------------------------------------------
CREATE TABLE feature_flags (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  key         TEXT        NOT NULL UNIQUE,
  value       TEXT        NOT NULL, -- JSON-encoded
  description TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by  TEXT
);

-- ---------------------------------------------------------------------------
-- updated_at trigger (applied to tables that need it)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_shows_updated_at
  BEFORE UPDATE ON shows
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_game_definitions_updated_at
  BEFORE UPDATE ON game_definitions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_play_clips_updated_at
  BEFORE UPDATE ON play_clips
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_feature_flags_updated_at
  BEFORE UPDATE ON feature_flags
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
