-- Ensure game package row exists for FK
INSERT INTO game_packages (id, name, version, description, manifest, bundle_url, is_enabled)
VALUES ('knife_at_center', 'Knife Hit', '1.0.0', 'Throw knives at the spinning wheel', '{}', '', false)
ON CONFLICT (id) DO NOTHING;

DELETE FROM game_levels WHERE game_package_id = 'knife_at_center';

INSERT INTO game_levels (game_package_id, name, config) VALUES
('knife_at_center', 'Level1',  '{"wheelSprite":"level1spin-sheet0.png","rotationType":"rotate","rotationSpeed":180,"throwCount":7,"preplacedKnives":[],"apples":[{"x":240,"y":150}],"knifeSkin":1,"timeLimitMs":30000}'),
('knife_at_center', 'Level2',  '{"wheelSprite":"level1spin2-sheet0.png","rotationType":"rotate","rotationSpeed":180,"throwCount":7,"preplacedKnives":[{"angleDeg":90}],"apples":[{"x":240,"y":150}],"knifeSkin":2,"timeLimitMs":30000}'),
('knife_at_center', 'Level3',  '{"wheelSprite":"level1spin3-sheet0.png","rotationType":"rotate","rotationSpeed":180,"throwCount":7,"preplacedKnives":[{"angleDeg":60},{"angleDeg":180}],"apples":[{"x":200,"y":160}],"knifeSkin":3,"timeLimitMs":30000}'),
('knife_at_center', 'Level4',  '{"wheelSprite":"level1spin4-sheet0.png","rotationType":"rotate","rotationSpeed":180,"throwCount":6,"preplacedKnives":[{"angleDeg":45},{"angleDeg":135}],"apples":[{"x":280,"y":160}],"knifeSkin":4,"timeLimitMs":28000}'),
('knife_at_center', 'Level5',  '{"wheelSprite":"level1spin5-sheet0.png","rotationType":"rotate","rotationSpeed":-180,"throwCount":6,"preplacedKnives":[{"angleDeg":30},{"angleDeg":150},{"angleDeg":270}],"apples":[],"knifeSkin":5,"timeLimitMs":28000}'),
('knife_at_center', 'Level6',  '{"wheelSprite":"level1spin6-sheet0.png","rotationType":"rotate","rotationSpeed":-120,"throwCount":6,"preplacedKnives":[{"angleDeg":0},{"angleDeg":120},{"angleDeg":240}],"apples":[{"x":240,"y":150}],"knifeSkin":6,"timeLimitMs":25000}'),
('knife_at_center', 'Level7',  '{"wheelSprite":"level1spin7-sheet0.png","rotationType":"sineextended","oscillationPeriod":7,"oscillationMagnitude":250,"throwCount":5,"preplacedKnives":[{"angleDeg":45},{"angleDeg":135},{"angleDeg":225}],"apples":[{"x":200,"y":140},{"x":280,"y":140}],"knifeSkin":7,"timeLimitMs":25000}'),
('knife_at_center', 'Level8',  '{"wheelSprite":"level1spin8-sheet0.png","rotationType":"rotate","rotationSpeed":-150,"throwCount":6,"preplacedKnives":[{"angleDeg":60},{"angleDeg":180},{"angleDeg":300}],"apples":[],"knifeSkin":8,"timeLimitMs":25000}'),
('knife_at_center', 'Level9',  '{"wheelSprite":"level1spin9-sheet0.png","rotationType":"rotate","rotationSpeed":-160,"throwCount":5,"preplacedKnives":[{"angleDeg":0},{"angleDeg":90},{"angleDeg":180},{"angleDeg":270}],"apples":[{"x":240,"y":140}],"knifeSkin":9,"timeLimitMs":22000}'),
('knife_at_center', 'Level10', '{"wheelSprite":"level1spin10-sheet0.png","rotationType":"sineextended","oscillationPeriod":5,"oscillationMagnitude":250,"throwCount":5,"preplacedKnives":[{"angleDeg":30},{"angleDeg":150},{"angleDeg":270}],"apples":[{"x":210,"y":150},{"x":270,"y":150}],"knifeSkin":10,"timeLimitMs":22000}'),
('knife_at_center', 'Level11', '{"wheelSprite":"level1spin11-sheet0.png","rotationType":"rotate","rotationSpeed":-180,"throwCount":5,"preplacedKnives":[{"angleDeg":0},{"angleDeg":72},{"angleDeg":144},{"angleDeg":216},{"angleDeg":288}],"apples":[],"knifeSkin":11,"timeLimitMs":20000}'),
('knife_at_center', 'Level12', '{"wheelSprite":"level1spin-sheet0.png","rotationType":"rotate","rotationSpeed":200,"throwCount":5,"preplacedKnives":[{"angleDeg":45},{"angleDeg":135},{"angleDeg":225},{"angleDeg":315}],"apples":[{"x":240,"y":140}],"knifeSkin":12,"timeLimitMs":20000}'),
('knife_at_center', 'Level13', '{"wheelSprite":"level1spin2-sheet0.png","rotationType":"sineextended","oscillationPeriod":5,"oscillationMagnitude":250,"throwCount":4,"preplacedKnives":[{"angleDeg":0},{"angleDeg":60},{"angleDeg":120},{"angleDeg":180},{"angleDeg":240}],"apples":[],"knifeSkin":13,"timeLimitMs":18000}'),
('knife_at_center', 'Level14', '{"wheelSprite":"level1spin3-sheet0.png","rotationType":"rotate","rotationSpeed":100,"throwCount":4,"preplacedKnives":[{"angleDeg":30},{"angleDeg":90},{"angleDeg":150},{"angleDeg":210},{"angleDeg":330}],"apples":[{"x":240,"y":140}],"knifeSkin":14,"timeLimitMs":18000}'),
('knife_at_center', 'Level15', '{"wheelSprite":"level1spin4-sheet0.png","rotationType":"rotate","rotationSpeed":300,"throwCount":4,"preplacedKnives":[{"angleDeg":0},{"angleDeg":60},{"angleDeg":120},{"angleDeg":180},{"angleDeg":240},{"angleDeg":300}],"apples":[],"knifeSkin":15,"timeLimitMs":15000}'),
('knife_at_center', 'Level16', '{"wheelSprite":"level1spin5-sheet0.png","rotationType":"sineextended","oscillationPeriod":6,"oscillationMagnitude":150,"throwCount":4,"preplacedKnives":[{"angleDeg":0},{"angleDeg":50},{"angleDeg":140},{"angleDeg":200},{"angleDeg":280}],"apples":[{"x":240,"y":150}],"knifeSkin":16,"timeLimitMs":15000}'),
('knife_at_center', 'Level17', '{"wheelSprite":"level1spin6-sheet0.png","rotationType":"rotate","rotationSpeed":300,"throwCount":3,"preplacedKnives":[{"angleDeg":0},{"angleDeg":45},{"angleDeg":120},{"angleDeg":180},{"angleDeg":225},{"angleDeg":300}],"apples":[],"knifeSkin":17,"timeLimitMs":15000}'),
('knife_at_center', 'Level18', '{"wheelSprite":"level1spin7-sheet0.png","rotationType":"sineextended","oscillationPeriod":5,"oscillationMagnitude":360,"throwCount":3,"preplacedKnives":[{"angleDeg":20},{"angleDeg":80},{"angleDeg":140},{"angleDeg":200},{"angleDeg":260},{"angleDeg":320}],"apples":[{"x":240,"y":140}],"knifeSkin":18,"timeLimitMs":12000}'),
('knife_at_center', 'Level19', '{"wheelSprite":"level1spin8-sheet0.png","rotationType":"sineextended","oscillationPeriod":12,"oscillationMagnitude":360,"throwCount":3,"preplacedKnives":[{"angleDeg":0},{"angleDeg":45},{"angleDeg":90},{"angleDeg":150},{"angleDeg":210},{"angleDeg":270},{"angleDeg":330}],"apples":[],"knifeSkin":19,"timeLimitMs":12000}'),
('knife_at_center', 'Level20', '{"wheelSprite":"level1spin9-sheet0.png","rotationType":"sineextended","oscillationPeriod":4,"oscillationMagnitude":360,"throwCount":3,"preplacedKnives":[{"angleDeg":0},{"angleDeg":40},{"angleDeg":100},{"angleDeg":160},{"angleDeg":220},{"angleDeg":280},{"angleDeg":340}],"apples":[],"knifeSkin":20,"timeLimitMs":10000}'),
('knife_at_center', 'Level21', '{"wheelSprite":"level1spin10-sheet0.png","rotationType":"rotate","rotationSpeed":360,"throwCount":3,"preplacedKnives":[{"angleDeg":0},{"angleDeg":40},{"angleDeg":80},{"angleDeg":130},{"angleDeg":180},{"angleDeg":230},{"angleDeg":280},{"angleDeg":330}],"apples":[],"knifeSkin":1,"timeLimitMs":10000}'),
('knife_at_center', 'Boss1',   '{"wheelSprite":"level1spin11-sheet0.png","rotationType":"rotate","rotationSpeed":-180,"throwCount":5,"preplacedKnives":[{"angleDeg":0},{"angleDeg":72},{"angleDeg":144},{"angleDeg":216},{"angleDeg":288}],"apples":[{"x":210,"y":140},{"x":270,"y":140}],"knifeSkin":8,"timeLimitMs":20000}'),
('knife_at_center', 'Boss2',   '{"wheelSprite":"level1spin-sheet0.png","rotationType":"rotate","rotationSpeed":-200,"throwCount":4,"preplacedKnives":[{"angleDeg":0},{"angleDeg":60},{"angleDeg":120},{"angleDeg":180},{"angleDeg":240},{"angleDeg":300}],"apples":[{"x":240,"y":140}],"knifeSkin":12,"timeLimitMs":18000}'),
('knife_at_center', 'Boss3',   '{"wheelSprite":"level1spin3-sheet0.png","rotationType":"oscillate","oscillationPeriod":9,"oscillationMagnitude":500,"throwCount":4,"preplacedKnives":[{"angleDeg":0},{"angleDeg":50},{"angleDeg":110},{"angleDeg":170},{"angleDeg":230},{"angleDeg":290},{"angleDeg":350}],"apples":[],"knifeSkin":15,"timeLimitMs":15000}'),
('knife_at_center', 'Boss4',   '{"wheelSprite":"level1spin5-sheet0.png","rotationType":"oscillate","oscillationPeriod":10,"oscillationMagnitude":-360,"throwCount":3,"preplacedKnives":[{"angleDeg":0},{"angleDeg":45},{"angleDeg":90},{"angleDeg":135},{"angleDeg":200},{"angleDeg":260},{"angleDeg":320}],"apples":[{"x":240,"y":140}],"knifeSkin":18,"timeLimitMs":12000}'),
('knife_at_center', 'Boss5',   '{"wheelSprite":"level1spin7-sheet0.png","rotationType":"rotate","rotationSpeed":250,"throwCount":3,"preplacedKnives":[{"angleDeg":0},{"angleDeg":40},{"angleDeg":80},{"angleDeg":130},{"angleDeg":180},{"angleDeg":230},{"angleDeg":280},{"angleDeg":330}],"apples":[],"knifeSkin":20,"timeLimitMs":10000}'),
('knife_at_center', 'Boss6',   '{"wheelSprite":"level1spin9-sheet0.png","rotationType":"rotate","rotationSpeed":-280,"throwCount":3,"preplacedKnives":[{"angleDeg":0},{"angleDeg":35},{"angleDeg":80},{"angleDeg":125},{"angleDeg":170},{"angleDeg":215},{"angleDeg":260},{"angleDeg":310}],"apples":[],"knifeSkin":5,"timeLimitMs":10000}'),
('knife_at_center', 'Boss7',   '{"wheelSprite":"level1spin11-sheet0.png","rotationType":"oscillate","oscillationPeriod":7,"oscillationMagnitude":700,"throwCount":2,"preplacedKnives":[{"angleDeg":0},{"angleDeg":40},{"angleDeg":80},{"angleDeg":120},{"angleDeg":170},{"angleDeg":220},{"angleDeg":260},{"angleDeg":300},{"angleDeg":340}],"apples":[],"knifeSkin":10,"timeLimitMs":8000}')
ON CONFLICT (game_package_id, name) DO UPDATE SET config = EXCLUDED.config;
