-- Ensure game package row exists for FK
INSERT INTO game_packages (id, name, version, description, manifest, bundle_url, is_enabled)
VALUES ('hangman', 'Hangman', '1.0.0', 'Guess the word letter by letter before the hangman is complete', '{}', '', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO game_levels (game_package_id, name, config) VALUES
-- Animals (15 words)
('hangman', 'CROCODILE',   '{"clue":"Animals","answer":"CROCODILE"}'),
('hangman', 'ELEPHANT',    '{"clue":"Animals","answer":"ELEPHANT"}'),
('hangman', 'GIRAFFE',     '{"clue":"Animals","answer":"GIRAFFE"}'),
('hangman', 'PENGUIN',     '{"clue":"Animals","answer":"PENGUIN"}'),
('hangman', 'CHEETAH',     '{"clue":"Animals","answer":"CHEETAH"}'),
('hangman', 'GORILLA',     '{"clue":"Animals","answer":"GORILLA"}'),
('hangman', 'FLAMINGO',    '{"clue":"Animals","answer":"FLAMINGO"}'),
('hangman', 'KANGAROO',    '{"clue":"Animals","answer":"KANGAROO"}'),
('hangman', 'PORCUPINE',   '{"clue":"Animals","answer":"PORCUPINE"}'),
('hangman', 'CHAMELEON',   '{"clue":"Animals","answer":"CHAMELEON"}'),
('hangman', 'WOLVERINE',   '{"clue":"Animals","answer":"WOLVERINE"}'),
('hangman', 'PLATYPUS',    '{"clue":"Animals","answer":"PLATYPUS"}'),
('hangman', 'ARMADILLO',   '{"clue":"Animals","answer":"ARMADILLO"}'),
('hangman', 'RHINOCEROS',  '{"clue":"Animals","answer":"RHINOCEROS"}'),
('hangman', 'CHIMPANZEE',  '{"clue":"Animals","answer":"CHIMPANZEE"}'),
-- Countries (15 words)
('hangman', 'BRAZIL',      '{"clue":"Countries","answer":"BRAZIL"}'),
('hangman', 'MOROCCO',     '{"clue":"Countries","answer":"MOROCCO"}'),
('hangman', 'THAILAND',    '{"clue":"Countries","answer":"THAILAND"}'),
('hangman', 'PORTUGAL',    '{"clue":"Countries","answer":"PORTUGAL"}'),
('hangman', 'ARGENTINA',   '{"clue":"Countries","answer":"ARGENTINA"}'),
('hangman', 'VIETNAM',     '{"clue":"Countries","answer":"VIETNAM"}'),
('hangman', 'ETHIOPIA',    '{"clue":"Countries","answer":"ETHIOPIA"}'),
('hangman', 'CAMBODIA',    '{"clue":"Countries","answer":"CAMBODIA"}'),
('hangman', 'PARAGUAY',    '{"clue":"Countries","answer":"PARAGUAY"}'),
('hangman', 'ZIMBABWE',    '{"clue":"Countries","answer":"ZIMBABWE"}'),
('hangman', 'INDONESIA',   '{"clue":"Countries","answer":"INDONESIA"}'),
('hangman', 'VENEZUELA',   '{"clue":"Countries","answer":"VENEZUELA"}'),
('hangman', 'MOZAMBIQUE',  '{"clue":"Countries","answer":"MOZAMBIQUE"}'),
('hangman', 'BANGLADESH',  '{"clue":"Countries","answer":"BANGLADESH"}'),
('hangman', 'KAZAKHSTAN',  '{"clue":"Countries","answer":"KAZAKHSTAN"}'),
-- Movies (15 words)
('hangman', 'INCEPTION',   '{"clue":"Movies","answer":"INCEPTION"}'),
('hangman', 'GLADIATOR',   '{"clue":"Movies","answer":"GLADIATOR"}'),
('hangman', 'INTERSTELLAR','{"clue":"Movies","answer":"INTERSTELLAR"}'),
('hangman', 'BRAVEHEART',  '{"clue":"Movies","answer":"BRAVEHEART"}'),
('hangman', 'PARASITE',    '{"clue":"Movies","answer":"PARASITE"}'),
('hangman', 'SPOTLIGHT',   '{"clue":"Movies","answer":"SPOTLIGHT"}'),
('hangman', 'WHIPLASH',    '{"clue":"Movies","answer":"WHIPLASH"}'),
('hangman', 'MEMENTO',     '{"clue":"Movies","answer":"MEMENTO"}'),
('hangman', 'ARRIVAL',     '{"clue":"Movies","answer":"ARRIVAL"}'),
('hangman', 'HEREDITARY',  '{"clue":"Movies","answer":"HEREDITARY"}'),
('hangman', 'MOONLIGHT',   '{"clue":"Movies","answer":"MOONLIGHT"}'),
('hangman', 'JOKER',       '{"clue":"Movies","answer":"JOKER"}'),
('hangman', 'DUNKIRK',     '{"clue":"Movies","answer":"DUNKIRK"}'),
('hangman', 'TENET',       '{"clue":"Movies","answer":"TENET"}'),
('hangman', 'OPPENHEIMER', '{"clue":"Movies","answer":"OPPENHEIMER"}'),
-- Sports (10 words)
('hangman', 'BADMINTON',   '{"clue":"Sports","answer":"BADMINTON"}'),
('hangman', 'VOLLEYBALL',  '{"clue":"Sports","answer":"VOLLEYBALL"}'),
('hangman', 'WRESTLING',   '{"clue":"Sports","answer":"WRESTLING"}'),
('hangman', 'FENCING',     '{"clue":"Sports","answer":"FENCING"}'),
('hangman', 'ARCHERY',     '{"clue":"Sports","answer":"ARCHERY"}'),
('hangman', 'KAYAKING',    '{"clue":"Sports","answer":"KAYAKING"}'),
('hangman', 'TRIATHLON',   '{"clue":"Sports","answer":"TRIATHLON"}'),
('hangman', 'BOBSLED',     '{"clue":"Sports","answer":"BOBSLED"}'),
('hangman', 'PENTATHLON',  '{"clue":"Sports","answer":"PENTATHLON"}'),
('hangman', 'DISCUS',      '{"clue":"Sports","answer":"DISCUS"}'),
-- Food & Drinks (10 words)
('hangman', 'BRUSCHETTA',  '{"clue":"Food & Drinks","answer":"BRUSCHETTA"}'),
('hangman', 'TIRAMISU',    '{"clue":"Food & Drinks","answer":"TIRAMISU"}'),
('hangman', 'GUACAMOLE',   '{"clue":"Food & Drinks","answer":"GUACAMOLE"}'),
('hangman', 'QUESADILLA',  '{"clue":"Food & Drinks","answer":"QUESADILLA"}'),
('hangman', 'CAPPUCCINO',  '{"clue":"Food & Drinks","answer":"CAPPUCCINO"}'),
('hangman', 'CROISSANT',   '{"clue":"Food & Drinks","answer":"CROISSANT"}'),
('hangman', 'MARMALADE',   '{"clue":"Food & Drinks","answer":"MARMALADE"}'),
('hangman', 'COLESLAW',    '{"clue":"Food & Drinks","answer":"COLESLAW"}'),
('hangman', 'PROSCIUTTO',  '{"clue":"Food & Drinks","answer":"PROSCIUTTO"}'),
('hangman', 'GAZPACHO',    '{"clue":"Food & Drinks","answer":"GAZPACHO"}'),
-- Technology (10 words)
('hangman', 'ALGORITHM',   '{"clue":"Technology","answer":"ALGORITHM"}'),
('hangman', 'BLOCKCHAIN',  '{"clue":"Technology","answer":"BLOCKCHAIN"}'),
('hangman', 'KUBERNETES',  '{"clue":"Technology","answer":"KUBERNETES"}'),
('hangman', 'JAVASCRIPT',  '{"clue":"Technology","answer":"JAVASCRIPT"}'),
('hangman', 'BANDWIDTH',   '{"clue":"Technology","answer":"BANDWIDTH"}'),
('hangman', 'ENCRYPTION',  '{"clue":"Technology","answer":"ENCRYPTION"}'),
('hangman', 'FRAMEWORK',   '{"clue":"Technology","answer":"FRAMEWORK"}'),
('hangman', 'DEBUGGING',   '{"clue":"Technology","answer":"DEBUGGING"}'),
('hangman', 'MIDDLEWARE',  '{"clue":"Technology","answer":"MIDDLEWARE"}'),
('hangman', 'REPOSITORY',  '{"clue":"Technology","answer":"REPOSITORY"}'),
-- Music (10 words)
('hangman', 'SAXOPHONE',   '{"clue":"Music","answer":"SAXOPHONE"}'),
('hangman', 'ORCHESTRA',   '{"clue":"Music","answer":"ORCHESTRA"}'),
('hangman', 'HARMONICA',   '{"clue":"Music","answer":"HARMONICA"}'),
('hangman', 'XYLOPHONE',   '{"clue":"Music","answer":"XYLOPHONE"}'),
('hangman', 'ACCORDION',   '{"clue":"Music","answer":"ACCORDION"}'),
('hangman', 'SYMPHONY',    '{"clue":"Music","answer":"SYMPHONY"}'),
('hangman', 'CONDUCTOR',   '{"clue":"Music","answer":"CONDUCTOR"}'),
('hangman', 'CRESCENDO',   '{"clue":"Music","answer":"CRESCENDO"}'),
('hangman', 'BASSLINE',    '{"clue":"Music","answer":"BASSLINE"}'),
('hangman', 'TAMBOURINE',  '{"clue":"Music","answer":"TAMBOURINE"}'),
-- Science (10 words)
('hangman', 'HYDROGEN',    '{"clue":"Science","answer":"HYDROGEN"}'),
('hangman', 'PHOTOSYNTHESIS','{"clue":"Science","answer":"PHOTOSYNTHESIS"}'),
('hangman', 'CHROMOSOME',  '{"clue":"Science","answer":"CHROMOSOME"}'),
('hangman', 'MAGNETISM',   '{"clue":"Science","answer":"MAGNETISM"}'),
('hangman', 'NEUTRON',     '{"clue":"Science","answer":"NEUTRON"}'),
('hangman', 'CATALYST',    '{"clue":"Science","answer":"CATALYST"}'),
('hangman', 'ISOTOPE',     '{"clue":"Science","answer":"ISOTOPE"}'),
('hangman', 'MOLECULE',    '{"clue":"Science","answer":"MOLECULE"}'),
('hangman', 'OSMOSIS',     '{"clue":"Science","answer":"OSMOSIS"}'),
('hangman', 'RADIATION',   '{"clue":"Science","answer":"RADIATION"}'),
-- Professions (10 words)
('hangman', 'ARCHITECT',   '{"clue":"Professions","answer":"ARCHITECT"}'),
('hangman', 'PHARMACIST',  '{"clue":"Professions","answer":"PHARMACIST"}'),
('hangman', 'RADIOLOGIST',  '{"clue":"Professions","answer":"RADIOLOGIST"}'),
('hangman', 'CHOREOGRAPHER','{"clue":"Professions","answer":"CHOREOGRAPHER"}'),
('hangman', 'VETERINARIAN', '{"clue":"Professions","answer":"VETERINARIAN"}'),
('hangman', 'SOMMELIER',   '{"clue":"Professions","answer":"SOMMELIER"}'),
('hangman', 'CARDIOLOGIST', '{"clue":"Professions","answer":"CARDIOLOGIST"}'),
('hangman', 'ARCHAEOLOGIST','{"clue":"Professions","answer":"ARCHAEOLOGIST"}'),
('hangman', 'METEOROLOGIST','{"clue":"Professions","answer":"METEOROLOGIST"}'),
('hangman', 'EPIDEMIOLOGIST','{"clue":"Professions","answer":"EPIDEMIOLOGIST"}')
ON CONFLICT (game_package_id, name) DO UPDATE SET config = EXCLUDED.config;
