/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/live` | `/live`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playclips` | `/playclips`; params?: Router.UnknownInputParams; } | { pathname: `/game/trivia`; params?: Router.UnknownInputParams; } | { pathname: `/show/[showId]`, params: Router.UnknownInputParams & { showId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/live` | `/live`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/playclips` | `/playclips`; params?: Router.UnknownOutputParams; } | { pathname: `/game/trivia`; params?: Router.UnknownOutputParams; } | { pathname: `/show/[showId]`, params: Router.UnknownOutputParams & { showId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/live${`?${string}` | `#${string}` | ''}` | `/live${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/playclips${`?${string}` | `#${string}` | ''}` | `/playclips${`?${string}` | `#${string}` | ''}` | `/game/trivia${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/live` | `/live`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playclips` | `/playclips`; params?: Router.UnknownInputParams; } | { pathname: `/game/trivia`; params?: Router.UnknownInputParams; } | `/show/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/show/[showId]`, params: Router.UnknownInputParams & { showId: string | number; } };
    }
  }
}
