-- Seed 105 hangman words across 9 categories
-- Idempotent: ON CONFLICT updates config

INSERT INTO game_levels (game_package_id, name, config) VALUES
  ('hangman', 'ACCORDION', '{"clue": "Music", "answer": "ACCORDION"}'),
  ('hangman', 'ALGORITHM', '{"clue": "Technology", "answer": "ALGORITHM"}'),
  ('hangman', 'ARCHAEOLOGIST', '{"clue": "Professions", "answer": "ARCHAEOLOGIST"}'),
  ('hangman', 'ARCHERY', '{"clue": "Sports", "answer": "ARCHERY"}'),
  ('hangman', 'ARCHITECT', '{"clue": "Professions", "answer": "ARCHITECT"}'),
  ('hangman', 'ARGENTINA', '{"clue": "Countries", "answer": "ARGENTINA"}'),
  ('hangman', 'ARMADILLO', '{"clue": "Animals", "answer": "ARMADILLO"}'),
  ('hangman', 'ARRIVAL', '{"clue": "Movies", "answer": "ARRIVAL"}'),
  ('hangman', 'BADMINTON', '{"clue": "Sports", "answer": "BADMINTON"}'),
  ('hangman', 'BANDWIDTH', '{"clue": "Technology", "answer": "BANDWIDTH"}'),
  ('hangman', 'BANGLADESH', '{"clue": "Countries", "answer": "BANGLADESH"}'),
  ('hangman', 'BASSLINE', '{"clue": "Music", "answer": "BASSLINE"}'),
  ('hangman', 'BLOCKCHAIN', '{"clue": "Technology", "answer": "BLOCKCHAIN"}'),
  ('hangman', 'BOBSLED', '{"clue": "Sports", "answer": "BOBSLED"}'),
  ('hangman', 'BRAVEHEART', '{"clue": "Movies", "answer": "BRAVEHEART"}'),
  ('hangman', 'BRAZIL', '{"clue": "Countries", "answer": "BRAZIL"}'),
  ('hangman', 'BRUSCHETTA', '{"clue": "Food & Drinks", "answer": "BRUSCHETTA"}'),
  ('hangman', 'CAMBODIA', '{"clue": "Countries", "answer": "CAMBODIA"}'),
  ('hangman', 'CAPPUCCINO', '{"clue": "Food & Drinks", "answer": "CAPPUCCINO"}'),
  ('hangman', 'CARDIOLOGIST', '{"clue": "Professions", "answer": "CARDIOLOGIST"}'),
  ('hangman', 'CATALYST', '{"clue": "Science", "answer": "CATALYST"}'),
  ('hangman', 'CHAMELEON', '{"clue": "Animals", "answer": "CHAMELEON"}'),
  ('hangman', 'CHEETAH', '{"clue": "Animals", "answer": "CHEETAH"}'),
  ('hangman', 'CHIMPANZEE', '{"clue": "Animals", "answer": "CHIMPANZEE"}'),
  ('hangman', 'CHOREOGRAPHER', '{"clue": "Professions", "answer": "CHOREOGRAPHER"}'),
  ('hangman', 'CHROMOSOME', '{"clue": "Science", "answer": "CHROMOSOME"}'),
  ('hangman', 'COLESLAW', '{"clue": "Food & Drinks", "answer": "COLESLAW"}'),
  ('hangman', 'CONDUCTOR', '{"clue": "Music", "answer": "CONDUCTOR"}'),
  ('hangman', 'CRESCENDO', '{"clue": "Music", "answer": "CRESCENDO"}'),
  ('hangman', 'CROCODILE', '{"clue": "Animals", "answer": "CROCODILE"}'),
  ('hangman', 'CROISSANT', '{"clue": "Food & Drinks", "answer": "CROISSANT"}'),
  ('hangman', 'DEBUGGING', '{"clue": "Technology", "answer": "DEBUGGING"}'),
  ('hangman', 'DISCUS', '{"clue": "Sports", "answer": "DISCUS"}'),
  ('hangman', 'DUNKIRK', '{"clue": "Movies", "answer": "DUNKIRK"}'),
  ('hangman', 'ELEPHANT', '{"clue": "Animals", "answer": "ELEPHANT"}'),
  ('hangman', 'ENCRYPTION', '{"clue": "Technology", "answer": "ENCRYPTION"}'),
  ('hangman', 'EPIDEMIOLOGIST', '{"clue": "Professions", "answer": "EPIDEMIOLOGIST"}'),
  ('hangman', 'ETHIOPIA', '{"clue": "Countries", "answer": "ETHIOPIA"}'),
  ('hangman', 'FENCING', '{"clue": "Sports", "answer": "FENCING"}'),
  ('hangman', 'FLAMINGO', '{"clue": "Animals", "answer": "FLAMINGO"}'),
  ('hangman', 'FRAMEWORK', '{"clue": "Technology", "answer": "FRAMEWORK"}'),
  ('hangman', 'GAZPACHO', '{"clue": "Food & Drinks", "answer": "GAZPACHO"}'),
  ('hangman', 'GIRAFFE', '{"clue": "Animals", "answer": "GIRAFFE"}'),
  ('hangman', 'GLADIATOR', '{"clue": "Movies", "answer": "GLADIATOR"}'),
  ('hangman', 'GORILLA', '{"clue": "Animals", "answer": "GORILLA"}'),
  ('hangman', 'GUACAMOLE', '{"clue": "Food & Drinks", "answer": "GUACAMOLE"}'),
  ('hangman', 'HARMONICA', '{"clue": "Music", "answer": "HARMONICA"}'),
  ('hangman', 'HEREDITARY', '{"clue": "Movies", "answer": "HEREDITARY"}'),
  ('hangman', 'HYDROGEN', '{"clue": "Science", "answer": "HYDROGEN"}'),
  ('hangman', 'INCEPTION', '{"clue": "Movies", "answer": "INCEPTION"}'),
  ('hangman', 'INDONESIA', '{"clue": "Countries", "answer": "INDONESIA"}'),
  ('hangman', 'INTERSTELLAR', '{"clue": "Movies", "answer": "INTERSTELLAR"}'),
  ('hangman', 'ISOTOPE', '{"clue": "Science", "answer": "ISOTOPE"}'),
  ('hangman', 'JAVASCRIPT', '{"clue": "Technology", "answer": "JAVASCRIPT"}'),
  ('hangman', 'JOKER', '{"clue": "Movies", "answer": "JOKER"}'),
  ('hangman', 'KANGAROO', '{"clue": "Animals", "answer": "KANGAROO"}'),
  ('hangman', 'KAYAKING', '{"clue": "Sports", "answer": "KAYAKING"}'),
  ('hangman', 'KAZAKHSTAN', '{"clue": "Countries", "answer": "KAZAKHSTAN"}'),
  ('hangman', 'KUBERNETES', '{"clue": "Technology", "answer": "KUBERNETES"}'),
  ('hangman', 'MAGNETISM', '{"clue": "Science", "answer": "MAGNETISM"}'),
  ('hangman', 'MARMALADE', '{"clue": "Food & Drinks", "answer": "MARMALADE"}'),
  ('hangman', 'MEMENTO', '{"clue": "Movies", "answer": "MEMENTO"}'),
  ('hangman', 'METEOROLOGIST', '{"clue": "Professions", "answer": "METEOROLOGIST"}'),
  ('hangman', 'MIDDLEWARE', '{"clue": "Technology", "answer": "MIDDLEWARE"}'),
  ('hangman', 'MOLECULE', '{"clue": "Science", "answer": "MOLECULE"}'),
  ('hangman', 'MOONLIGHT', '{"clue": "Movies", "answer": "MOONLIGHT"}'),
  ('hangman', 'MOROCCO', '{"clue": "Countries", "answer": "MOROCCO"}'),
  ('hangman', 'MOZAMBIQUE', '{"clue": "Countries", "answer": "MOZAMBIQUE"}'),
  ('hangman', 'NEUTRON', '{"clue": "Science", "answer": "NEUTRON"}'),
  ('hangman', 'OPPENHEIMER', '{"clue": "Movies", "answer": "OPPENHEIMER"}'),
  ('hangman', 'ORCHESTRA', '{"clue": "Music", "answer": "ORCHESTRA"}'),
  ('hangman', 'OSMOSIS', '{"clue": "Science", "answer": "OSMOSIS"}'),
  ('hangman', 'PARAGUAY', '{"clue": "Countries", "answer": "PARAGUAY"}'),
  ('hangman', 'PARASITE', '{"clue": "Movies", "answer": "PARASITE"}'),
  ('hangman', 'PENGUIN', '{"clue": "Animals", "answer": "PENGUIN"}'),
  ('hangman', 'PENTATHLON', '{"clue": "Sports", "answer": "PENTATHLON"}'),
  ('hangman', 'PHARMACIST', '{"clue": "Professions", "answer": "PHARMACIST"}'),
  ('hangman', 'PHOTOSYNTHESIS', '{"clue": "Science", "answer": "PHOTOSYNTHESIS"}'),
  ('hangman', 'PLATYPUS', '{"clue": "Animals", "answer": "PLATYPUS"}'),
  ('hangman', 'PORCUPINE', '{"clue": "Animals", "answer": "PORCUPINE"}'),
  ('hangman', 'PORTUGAL', '{"clue": "Countries", "answer": "PORTUGAL"}'),
  ('hangman', 'PROSCIUTTO', '{"clue": "Food & Drinks", "answer": "PROSCIUTTO"}'),
  ('hangman', 'QUESADILLA', '{"clue": "Food & Drinks", "answer": "QUESADILLA"}'),
  ('hangman', 'RADIATION', '{"clue": "Science", "answer": "RADIATION"}'),
  ('hangman', 'RADIOLOGIST', '{"clue": "Professions", "answer": "RADIOLOGIST"}'),
  ('hangman', 'REPOSITORY', '{"clue": "Technology", "answer": "REPOSITORY"}'),
  ('hangman', 'RHINOCEROS', '{"clue": "Animals", "answer": "RHINOCEROS"}'),
  ('hangman', 'SAXOPHONE', '{"clue": "Music", "answer": "SAXOPHONE"}'),
  ('hangman', 'SOMMELIER', '{"clue": "Professions", "answer": "SOMMELIER"}'),
  ('hangman', 'SPOTLIGHT', '{"clue": "Movies", "answer": "SPOTLIGHT"}'),
  ('hangman', 'SYMPHONY', '{"clue": "Music", "answer": "SYMPHONY"}'),
  ('hangman', 'TAMBOURINE', '{"clue": "Music", "answer": "TAMBOURINE"}'),
  ('hangman', 'TENET', '{"clue": "Movies", "answer": "TENET"}'),
  ('hangman', 'THAILAND', '{"clue": "Countries", "answer": "THAILAND"}'),
  ('hangman', 'TIRAMISU', '{"clue": "Food & Drinks", "answer": "TIRAMISU"}'),
  ('hangman', 'TRIATHLON', '{"clue": "Sports", "answer": "TRIATHLON"}'),
  ('hangman', 'VENEZUELA', '{"clue": "Countries", "answer": "VENEZUELA"}'),
  ('hangman', 'VETERINARIAN', '{"clue": "Professions", "answer": "VETERINARIAN"}'),
  ('hangman', 'VIETNAM', '{"clue": "Countries", "answer": "VIETNAM"}'),
  ('hangman', 'VOLLEYBALL', '{"clue": "Sports", "answer": "VOLLEYBALL"}'),
  ('hangman', 'WHIPLASH', '{"clue": "Movies", "answer": "WHIPLASH"}'),
  ('hangman', 'WOLVERINE', '{"clue": "Animals", "answer": "WOLVERINE"}'),
  ('hangman', 'WRESTLING', '{"clue": "Sports", "answer": "WRESTLING"}'),
  ('hangman', 'XYLOPHONE', '{"clue": "Music", "answer": "XYLOPHONE"}'),
  ('hangman', 'ZIMBABWE', '{"clue": "Countries", "answer": "ZIMBABWE"}')
ON CONFLICT (game_package_id, name) DO UPDATE SET config = EXCLUDED.config, updated_at = now();
