-- Seed 28 knife_at_center levels from Construct2 data.js
-- Run after the knife_at_center game package is uploaded

INSERT INTO game_levels (game_package_id, name, config) VALUES
  ('knife_at_center', 'Level1', '{"wheelSprite": "level1spin-sheet0.png", "throwCount": 7, "preplacedKnives": [], "apples": [], "rotationType": "rotate", "rotationSpeed": 180}'),
  ('knife_at_center', 'Level2', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 9, "preplacedKnives": [], "apples": [{"x": 240, "y": 129}], "rotationType": "rotate", "rotationSpeed": 180}'),
  ('knife_at_center', 'Level3', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 7, "preplacedKnives": [{"angleDeg": -90.2}, {"angleDeg": -1.7}], "apples": [], "rotationType": "rotate", "rotationSpeed": 180}'),
  ('knife_at_center', 'Level4', '{"wheelSprite": "level1spin3-sheet0.png", "throwCount": 9, "preplacedKnives": [{"angleDeg": -90.2}, {"angleDeg": 89.8}], "apples": [{"x": 390.1, "y": 280}], "rotationType": "rotate", "rotationSpeed": 180}'),
  ('knife_at_center', 'Level5', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 9, "preplacedKnives": [{"angleDeg": -1.7}], "apples": [], "rotationType": "rotate", "rotationSpeed": -180}'),
  ('knife_at_center', 'Level6', '{"wheelSprite": "level1spin3-sheet0.png", "throwCount": 9, "preplacedKnives": [{"angleDeg": -90.2}], "apples": [{"x": 297.7, "y": 140.3}], "rotationType": "rotate", "rotationSpeed": -120}'),
  ('knife_at_center', 'Level7', '{"wheelSprite": "level1spin4-sheet0.png", "throwCount": 10, "preplacedKnives": [{"angleDeg": -90.2}], "apples": [], "rotationType": "sine", "oscillationPeriod": 7, "oscillationMagnitude": 250}'),
  ('knife_at_center', 'Level8', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 10, "preplacedKnives": [{"angleDeg": -90.2}], "apples": [{"x": 347, "y": 174}, {"x": 98, "y": 328}], "rotationType": "rotate", "rotationSpeed": -150}'),
  ('knife_at_center', 'Level9', '{"wheelSprite": "level1spin3-sheet0.png", "throwCount": 10, "preplacedKnives": [{"angleDeg": -90.2}, {"angleDeg": 35.7}, {"angleDeg": 117.9}], "apples": [{"x": 347, "y": 174}, {"x": 98, "y": 328}], "rotationType": "rotate", "rotationSpeed": -160}'),
  ('knife_at_center', 'Level10', '{"wheelSprite": "level1spin4-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": -90.2}, {"angleDeg": 35.7}], "apples": [{"x": 98, "y": 328}], "rotationType": "sine", "oscillationPeriod": 5, "oscillationMagnitude": 250}'),
  ('knife_at_center', 'Level11', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": -115.4}, {"angleDeg": -63.4}, {"angleDeg": -89.0}], "apples": [], "rotationType": "rotate", "rotationSpeed": -180}'),
  ('knife_at_center', 'Level12', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 9, "preplacedKnives": [{"angleDeg": 0.0}, {"angleDeg": -44.0}, {"angleDeg": -89.0}], "apples": [{"x": 300, "y": 145}, {"x": 377, "y": 223}], "rotationType": "rotate", "rotationSpeed": 200}'),
  ('knife_at_center', 'Level13', '{"wheelSprite": "level1spin4-sheet0.png", "throwCount": 11, "preplacedKnives": [{"angleDeg": 137.4}, {"angleDeg": -44.0}, {"angleDeg": -137.4}, {"angleDeg": 44.0}], "apples": [], "rotationType": "sine", "oscillationPeriod": 5, "oscillationMagnitude": 250}'),
  ('knife_at_center', 'Level14', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": 180.0}, {"angleDeg": 0.0}], "apples": [], "rotationType": "rotate", "rotationSpeed": 100}'),
  ('knife_at_center', 'Level15', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 10, "preplacedKnives": [{"angleDeg": -44.0}, {"angleDeg": -137.4}, {"angleDeg": 90.0}], "apples": [{"x": 240, "y": 128}, {"x": 377, "y": 346}, {"x": 104, "y": 348}], "rotationType": "rotate", "rotationSpeed": 300}'),
  ('knife_at_center', 'Level16', '{"wheelSprite": "level1spin4-sheet0.png", "throwCount": 11, "preplacedKnives": [{"angleDeg": 0.0}, {"angleDeg": 180.0}], "apples": [], "rotationType": "sine", "oscillationPeriod": 6, "oscillationMagnitude": 150}'),
  ('knife_at_center', 'Level17', '{"wheelSprite": "level1spin3-sheet0.png", "throwCount": 10, "preplacedKnives": [{"angleDeg": -90.2}, {"angleDeg": 90.0}], "apples": [{"x": 347, "y": 174}, {"x": 98, "y": 328}], "rotationType": "rotate", "rotationSpeed": 300}'),
  ('knife_at_center', 'Level18', '{"wheelSprite": "level1spin4-sheet0.png", "throwCount": 14, "preplacedKnives": [{"angleDeg": -90.2}, {"angleDeg": 90.0}], "apples": [{"x": 347, "y": 174}, {"x": 115, "y": 368}, {"x": 365, "y": 368}, {"x": 132, "y": 173}], "rotationType": "sine", "oscillationPeriod": 5, "oscillationMagnitude": 360}'),
  ('knife_at_center', 'Level19', '{"wheelSprite": "level1spin4-sheet0.png", "throwCount": 7, "preplacedKnives": [{"angleDeg": 0.0}, {"angleDeg": 180.0}], "apples": [], "rotationType": "sine", "oscillationPeriod": 12, "oscillationMagnitude": 360}'),
  ('knife_at_center', 'Level20', '{"wheelSprite": "level1spin4-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": 0.0}, {"angleDeg": 180.0}], "apples": [], "rotationType": "sine", "oscillationPeriod": 4, "oscillationMagnitude": 360}'),
  ('knife_at_center', 'Level21', '{"wheelSprite": "level1spin2-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": -115.4}, {"angleDeg": -63.4}, {"angleDeg": -89.0}], "apples": [{"x": 170, "y": 414}, {"x": 240, "y": 431}, {"x": 308, "y": 415}], "rotationType": "rotate", "rotationSpeed": 360}'),
  ('knife_at_center', 'Boss1', '{"wheelSprite": "level1spin5-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": -90.2}, {"angleDeg": 127.8}, {"angleDeg": 16.1}], "apples": [{"x": 353, "y": 199}, {"x": 116, "y": 210}, {"x": 307, "y": 399}], "rotationType": "rotate", "rotationSpeed": -180}'),
  ('knife_at_center', 'Boss2', '{"wheelSprite": "level1spin6-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": -128.9}, {"angleDeg": 14.5}, {"angleDeg": -172.3}, {"angleDeg": 55.2}], "apples": [{"x": 116, "y": 210}, {"x": 361, "y": 366}], "rotationType": "rotate", "rotationSpeed": -200}'),
  ('knife_at_center', 'Boss3', '{"wheelSprite": "level1spin7-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": -141.6}, {"angleDeg": -39.5}, {"angleDeg": 165.6}, {"angleDeg": 12.8}], "apples": [{"x": 241, "y": 129}, {"x": 171, "y": 417}, {"x": 305, "y": 418}], "rotationType": "sine", "oscillationPeriod": 9, "oscillationMagnitude": 500}'),
  ('knife_at_center', 'Boss4', '{"wheelSprite": "level1spin8-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": 90.0}, {"angleDeg": 180.0}, {"angleDeg": -90.0}, {"angleDeg": 0.0}], "apples": [{"x": 349, "y": 176}, {"x": 138, "y": 393}, {"x": 345, "y": 390}, {"x": 129, "y": 176}], "rotationType": "sine", "oscillationPeriod": 10, "oscillationMagnitude": -360}'),
  ('knife_at_center', 'Boss5', '{"wheelSprite": "level1spin9-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": 180.0}, {"angleDeg": -90.0}, {"angleDeg": 0.0}], "apples": [{"x": 349, "y": 176}, {"x": 138, "y": 393}, {"x": 345, "y": 390}, {"x": 129, "y": 176}], "rotationType": "rotate", "rotationSpeed": 250}'),
  ('knife_at_center', 'Boss6', '{"wheelSprite": "level1spin10-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": 162.2}, {"angleDeg": -90.0}, {"angleDeg": 17.7}, {"angleDeg": 90.0}], "apples": [{"x": 349, "y": 176}, {"x": 129, "y": 176}], "rotationType": "rotate", "rotationSpeed": -280}'),
  ('knife_at_center', 'Boss7', '{"wheelSprite": "level1spin11-sheet0.png", "throwCount": 8, "preplacedKnives": [{"angleDeg": -141.6}, {"angleDeg": -39.5}, {"angleDeg": 165.6}, {"angleDeg": 12.8}, {"angleDeg": -110.9}, {"angleDeg": -69.8}], "apples": [{"x": 241, "y": 129}, {"x": 171, "y": 417}, {"x": 305, "y": 418}], "rotationType": "sine", "oscillationPeriod": 7, "oscillationMagnitude": 700}')
ON CONFLICT (game_package_id, name) DO UPDATE SET config = EXCLUDED.config, updated_at = now();
